# Generated by Django 4.2 on 2023-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_of_birth_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select Gender'), ('M', 'Man'), ('W', 'woman')], default='', max_length=1),
        ),
    ]
