# Generated by Django 4.2 on 2023-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('-', 'Select Gender'), ('M', 'Man'), ('W', 'woman')], default='', max_length=1),
        ),
    ]
