# Generated by Django 4.2 on 2023-05-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='uer',
            new_name='user',
        ),
    ]
